### ISSUE TITLE
MBPO cannot work on HumanoidTruncatedObsEnv and original Humanoid Env[Bug]

### ISSUE THREAD

**Issue by jity16** [facebookresearch/mbrl-lib#138] opened 2021-12-24 09:29 UTC
## Steps to reproduce

  1.  I tried to run MBPO on HumanoidTruncatedObsEnv with the default parameters in this repo but the final reward is around 180(seems like random policy and not work)
  2. I tried to run MBPO on original Humanoid env(without truncated obs) and still cannot work
  
and I have tried different seeds and they all cannot work

## Observed Results

  * The results of episode reward :
  
![image](https://user-images.githubusercontent.com/35065354/147340055-ce242117-7f62-4bdc-9a40-b3381e245eb6.png)

## Expected Results

  * The expected results (episode reward) may around 6k

**Comment by jity16** [comment] 2021-12-27 17:02
I think why MBPO cannot work may be caused by the third-party SAC used in this lib. 
I've tried to run the third-party SAC( only the SAC algorithm ) on gym___Halfcheetah environment, and I found critic loss of this sac explodes! I think this third-party SAC maybe not be implemented correctly. It's different from the results in another sac repo(https://github.com/pranz24/pytorch-soft-actor-critic). 
(1) this is the result (reward and critic loss from another sac repo):
<img src="https://user-images.githubusercontent.com/35065354/147491992-ab48864a-a1c0-4dce-a678-f37baab029b2.png" alt="alt text" width="300"><img src="https://user-images.githubusercontent.com/35065354/147492003-c73b75a3-a959-43fe-85c2-ed78c97d1091.png" alt="alt text" width="300">

(2) And this is the result from the third-party sac used in this repo:
<img src="https://user-images.githubusercontent.com/35065354/147492507-360d91f8-2f79-4aa9-9007-80910a8bd2c9.png" alt="alt text" width="300"><img src="https://user-images.githubusercontent.com/35065354/147492530-c0b1049a-7c05-4bb5-8242-ba4582de38bd.png" alt="alt text" width="300">


Thanks for considering my issue!

**Comment by Roythuly** [comment] 2021-12-28 02:40
I have the same problem in humanoid with MBPO. And I find the third party of SAC implemention in this repo (https://github.com/denisyarats/pytorch_sac), which is not satisfied in humanoid as:
![image](https://user-images.githubusercontent.com/57201828/147521595-e99ef945-55d1-494e-bbfa-a8779c69fa64.png)

I also try the repo (https://github.com/pranz24/pytorch-soft-actor-critic) and I get this result:
![image](https://user-images.githubusercontent.com/57201828/147521760-d183f1f1-4206-4089-992c-5bfb1d75a5b0.png)
as the result of @jity16 . Thus, I think that the problem of MBPO in humanoid may from the implemention of SAC.

**Comment by luisenp** [comment] 2021-12-28 03:38
Hi @jity16 and @Roythuly. Thanks a lot for looking into this! This is a known issue, as mentioned in our [paper](https://arxiv.org/abs/2104.10159), but I haven't yet tried changing the SAC implementation, so this is a good lead!

I'll try to test this with the MBPO into this as soon as possible. Unfortunately, everyone in my household is currently down with COVID (including me), so I'm taking a few days off to rest and get this out of the way. Hopefully will be able to work on this in 1-2 weeks.

**Comment by jity16** [comment] 2021-12-28 05:22
I'm very sorry to hear that. Take good care of yourself and wish you recover soon~

**Comment by luisenp** [comment] 2022-01-10 22:50
Hi @jity16. I started worked on this today, and have already an implementation with the other SAC working, but I haven't tested it yet. You can take a look in #142 if you are curious about progress. It's very likely not working yet, but just wanted to update this issue on the current progress.

**Comment by Roythuly** [comment] 2022-01-11 09:57
Thank you so much @luisenp and wish you and your family better sooner! I would like to try this repo. Thanks for your help!

**Comment by luisenp** [comment] 2022-01-17 22:23
Hi @jity16 @Roythuly.  I updated the new code a bit and fixed some bugs (#142). So far I've tested it with InvertedPendulum-v2 and it works well. I just launched a run with 10 seeds of HalfCheetah-v2 (which used to fail for some seeds), and will report results later. In the mean time, feel free to test again with Humanoid to see if it works well for you. Thanks!

**Comment by luisenp** [comment] 2022-01-19 18:36
Results on HalfCheetah-v2 are inconclusive and still having exploding losses in Humanoid. However, I noticed that plain SAC (no model) also fails when using automatic entropy tuning, which to my understanding is the default for MBPO, but not for pranz24's repo. So, I'll try running both cheetah and humanoid w/o entropy tuning and see if things improve.

**Comment by cvoelcker** [comment] 2022-01-20 17:27
Hi, I did similar experiments before the winter break (didn't get the time to write a comment here) and I found that one of the potential culprits for this is different layer initialization in the used SAC library (compared to i.e. stable-baselines). Colleagues have also found that NN initialization can have fairly large effects on the performance of SAC, so this might be an additional lead. I

**Comment by luisenp** [comment] 2022-01-20 17:38
HI @cvoelcker, thanks a lot for the comment. I've also seen model initialization to play an important role in model predictions as well.

For what is worth, Pranz's SAC works well for me in Humanoid with the right parameter settings, so in principle it should work with MBPO. However, there seems to be some strange interaction with the model predictions that causes exploding losses when using it in MBPO. 

If time allows, my plan is to play around today/tomorrow with adding some amount of real data to SAC's buffer in MBPO, and also compare stats of model predictions against the real data. 

Also, I'm curious if @jannerm ever experienced similar issues, and if he'd have any pointers here.

**Comment by luisenp** [comment] 2022-01-21 21:57
Hi all. As it turns out, I just found a silly bug that was probably the root cause of the issue. My make_env utility was setting the wrong termination function for Humanoid, and the model simulator ended using Ant's instead. I fixed this and launched a run a few hours ago and seems to be learning (R=850 so far, ~130k steps).

You can check the latest code in #142 if you want to try it out. I'm running experiments with 10 seeds on a few domains, and It's still unclear whether Pranz's library results in better performance, so I'll wait to have a clearer picture before merging that branch into main.

**Comment by RajGhugare19** [comment] 2022-01-30 04:39
Hello everyone! Does anyone know how MBPO (mbrl-lib or author's or any other implementation) performs on standard Ant-v2 and Humanoid-v2 tasks, without truncated observations that is. 
Thank you.

**Comment by bamos** [comment] 2022-01-30 14:53
> Hello everyone! Does anyone know how MBPO (mbrl-lib or author's or any other implementation) performs on standard Ant-v2 and Humanoid-v2 tasks, without truncated observations that is. Thank you.

I quickly tried SVG (https://arxiv.org/abs/2008.12775) on the versions without truncated observations. The IMU measurements were much more difficult to predict with the learned dynamics and in that setting, made it more likely for the policy to find wrong IMU predictions that gave unreasonably high and wrong reward/value estimates

**Comment by natolambert** [comment] 2022-01-30 16:24
IMU measurements should NOT be used in standard one-step models. I feel like there is such low hanging fruit here to make some model-based methods work better. We should add in some sort of integrator / separate prediction coupling when compared to velocities or positions... hmm. Feel free to ping me if anyone wants to investigate this or has clear info on the state-spaces for these environments and I can play with it.

**Comment by RajGhugare19** [comment] 2022-01-31 08:46
> I quickly tried SVG (https://arxiv.org/abs/2008.12775) on the versions without truncated observations. The IMU measurements were much more difficult to predict with the learned dynamics and in that setting, made it more likely for the policy to find wrong IMU predictions that gave unreasonably high and wrong reward/value estimates

Thanks for trying this out.

**Comment by luisenp** [comment] 2022-01-31 15:39
Update: Here are the results on humanoid (truncated obs) with 10 seeds, after tuning. I also get good results in all 6 environments of Figure 2 in the original paper, but I think I can still tune Ant and Walker a bit more. After that's done, I'll commit the best configs to #142, merge, and close this issue. Thanks everyone!

![image](https://user-images.githubusercontent.com/4759586/151823187-d9470413-f3e2-4bdc-8cc4-26e99ec2dc58.png)

**Comment by luisenp** [comment] 2022-02-03 16:53
Fixed by #142 :)

**Closed** 2022-02-03 16:52 UTC
Labels: bug

**Comment by shenao-zhang** [comment] 2022-07-03 11:05
> I think why MBPO cannot work may be caused by the third-party SAC used in this lib. I've tried to run the third-party SAC( only the SAC algorithm ) on gym___Humanoid-v2 environment, and I found critic loss of this sac explodes! I think this third-party SAC maybe not be implemented correctly. It's different from the results in another sac repo(https://github.com/pranz24/pytorch-soft-actor-critic). (1) this is the result (reward and critic loss from another sac repo): <img alt="alt text" width="300" src="https://user-images.githubusercontent.com/35065354/147491992-ab48864a-a1c0-4dce-a678-f37baab029b2.png"><img alt="alt text" width="300" src="https://user-images.githubusercontent.com/35065354/147492003-c73b75a3-a959-43fe-85c2-ed78c97d1091.png">
> 
> (2) And this is the result from the third-party sac used in this repo: <img alt="alt text" width="300" src="https://user-images.githubusercontent.com/35065354/147492507-360d91f8-2f79-4aa9-9007-80910a8bd2c9.png"><img alt="alt text" width="300" src="https://user-images.githubusercontent.com/35065354/147492530-c0b1049a-7c05-4bb5-8242-ba4582de38bd.png">
> 
> Thanks for considering my issue!

Hi @jity16 did you figure out why the critic loss explodes? I'm recently implementing BPTT and facing similar problems. Sorry for commenting on the closed issue.
